services:
  app:
    build: .
    container_name: php-app
    ports:
      - "8000:80"
    volumes:
      - ./index.php:/var/www/html/index.php
    depends_on:
      - db

  db:
    image: mysql
    container_name: mysql_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: "root"
      MYSQL_DATABASE: cajcms2
    volumes:
      - mysql-data:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - '8081:80'
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: root
      MYSQL_PASSWORD: ""

volumes:
  mysql-data:
